### PR TITLE
active users layout added issue(#8)

### PR DESCRIPTION
**Pull request by CulturalProfessor**
I have added a separate layout for active users and added realtime active-users list.

https://user-images.githubusercontent.com/92238941/219713393-bdc84026-668d-4f2b-8441-e130d9a320e5.mp4

### CODE REVIEW

**Comment by CulturalProfessor** [comment]
hey @swarnarkadas how can I resolve conflicts?

**Comment by swarnarkadas** [comment]
@CulturalProfessor, This is just insane. But due to a problem, What I would suggest is that please fork the repo again, make changes, and do send the same PR again. I will merge it

**Comment by swarnarkadas** [comment]
This is just insane. But due to a problem, What I would suggest is that please fork the repo again, make changes, and do send the same PR again. I will merge it

**Comment by CulturalProfessor** [comment]
> This is just insane. But due to a problem, What I would suggest is that please fork the repo again, make changes, and do send the same PR again. I will merge it

ok thanks,but what was the problem?

**Pull request closed without merging**
