### PR TITLE
Added encrypted chat feature

### PR DESCRIPTION
**Pull request by RishabhJain0721**
## Here is the video demonstration of how the encrypted chat feature works ##

[encryptedChatFunctionality.webm](https://user-images.githubusercontent.com/107767172/219694540-2937bc6b-caed-4557-974b-a80ca8ce86ba.webm)

### CODE REVIEW

**Comment by swarnarkadas** [comment]
@RishabhJain0721, This is just insane. But due to a problem, What I would suggest is that please fork the repo again, make changes, and do send the same PR again. I will merge it

**Comment by RishabhJain0721** [comment]
Alright I will do the required changes

**Comment by swarnarkadas** [comment]
@RishabhJain0721, just wait for a few hours before forking the repo. I will notify you personally. don't worry. There is a severe problem, will fix it soon.

**Comment by RishabhJain0721** [comment]
Alright no worries

**Comment by swarnarkadas** [comment]
Hey @RishabhJain0721, now all is ok. So, please fork the repo again, do the necessary changes, and send PR.

**Pull request closed without merging**
