### PR TITLE
Time functionality added

### PR DESCRIPTION
**Pull request by Laxmankohar**
image
image

### CODE REVIEW

**Review by swarnarkadas — CHANGES_REQUESTED** [review]
@Laxmankohar,  one can see only own message timing but not others. Try to fix it. Also, swap the place of the message and its time.

**Comment by Laxmankohar** [comment]
> @Laxmankohar, one can see only own message timing but not others. Try to fix it. Also, swap the place of the message and its time.

ok

**Comment by Laxmankohar** [comment]
Is it ok?

image

**Comment by swarnarkadas** [comment]
@Laxmankohar, yeah now it's kinda perfect.... do create a PR...will merge it

**Pull request merged**
